<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEvents($id)
    {
        $repository = $this->getEntityManager()->getRepository('AppBundle:Event');

        return $repository->getByFilter([
            'author' => $id
        ]);
    }
}
